name: umpsafyp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^7.3.1
  cupertino_icons: ^1.0.8
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  google_sign_in: ^6.2.1
  audioplayers: ^6.0.0
  http: ^1.2.1
  image_picker: ^1.1.1
  intl: ^0.19.0
  path_provider: ^2.1.5
  record: ^5.1.1
  url_launcher: ^6.2.6
  timeago: ^3.7.1
  latlong2: ^0.9.1
  geocoding: ^4.0.0
  geolocator: ^12.0.0
  curved_navigation_bar: ^1.0.6
  flutter_map: ^8.1.1
  flutter_local_notifications: ^19.2.1
  permission_handler: ^12.0.0+1
  firebase_storage: ^11.7.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

# Flutter launcher icons configuration (at root level)
flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/logo.png
    - lib/assets/images/google.png
    - lib/assets/images/dashboard1.png
