// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABuDc9XPwxFu0F-NuNu48KFzRE07gsCYA',
    appId: '1:102613975097:android:670c32daa2d31ad98b8de8',
    messagingSenderId: '102613975097',
    projectId: 'umpsasport',
    storageBucket: 'umpsasport.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAHmFrNqHmrwfNKsEFPbC7fCwGN2ouqHc',
    appId: '1:102613975097:ios:f20ac2b0479068678b8de8',
    messagingSenderId: '102613975097',
    projectId: 'umpsasport',
    storageBucket: 'umpsasport.firebasestorage.app',
    androidClientId: '102613975097-aakr9f52ia16n17n8h9m9h0fahvrh51d.apps.googleusercontent.com',
    iosClientId: '102613975097-mgs5h65sc62i87np0q3snedeu2t0vo87.apps.googleusercontent.com',
    iosBundleId: 'com.example.umpsafyp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKC9Y8XBusnNY9Gt5NytuG3WdyZAFFeB4',
    appId: '1:102613975097:web:37d82cdc5dd8e3368b8de8',
    messagingSenderId: '102613975097',
    projectId: 'umpsasport',
    authDomain: 'umpsasport.firebaseapp.com',
    storageBucket: 'umpsasport.firebasestorage.app',
    measurementId: 'G-GX52P4KDJ0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAHmFrNqHmrwfNKsEFPbC7fCwGN2ouqHc',
    appId: '1:102613975097:ios:f20ac2b0479068678b8de8',
    messagingSenderId: '102613975097',
    projectId: 'umpsasport',
    storageBucket: 'umpsasport.firebasestorage.app',
    androidClientId: '102613975097-aakr9f52ia16n17n8h9m9h0fahvrh51d.apps.googleusercontent.com',
    iosClientId: '102613975097-mgs5h65sc62i87np0q3snedeu2t0vo87.apps.googleusercontent.com',
    iosBundleId: 'com.example.umpsafyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKC9Y8XBusnNY9Gt5NytuG3WdyZAFFeB4',
    appId: '1:102613975097:web:18a68dc6341e09618b8de8',
    messagingSenderId: '102613975097',
    projectId: 'umpsasport',
    authDomain: 'umpsasport.firebaseapp.com',
    storageBucket: 'umpsasport.firebasestorage.app',
    measurementId: 'G-8KK0F3KHHP',
  );

}